[project]
name = "my_project"
version = "0.0.1"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "ipykernel>=7.2.0",
    "msal>=1.34.0",
    "python-dotenv>=1.2.1",
    "requests>=2.32.5",
]
